export const PROGRAMMING_ICONS = [
  {
    id: 1,
    value: 'Angular',
    iconPath: 'icons/svgs/angular.svg',
    ogpPath: 'icons/ogps/angular.png',
  },
  {
    id: 2,
    value: 'Backbone.js',
    iconPath: 'icons/svgs/backbonejs.svg',
    ogpPath: 'icons/ogps/backbonejs.png',
  },
  {
    id: 3,
    value: 'CakePHP',
    iconPath: 'icons/svgs/cakephp.svg',
    ogpPath: 'icons/ogps/cakephp.png',
  },
  {
    id: 4,
    value: 'CSS',
    iconPath: 'icons/svgs/css3.svg',
    ogpPath: 'icons/ogps/css3.png',
  },
  {
    id: 5,
    value: 'Dart',
    iconPath: 'icons/svgs/dart.svg',
    ogpPath: 'icons/ogps/dart.png',
  },
  {
    id: 6,
    value: 'Django',
    iconPath: 'icons/svgs/django.svg',
    ogpPath: 'icons/ogps/django.png',
  },
  {
    id: 7,
    value: 'Docker',
    iconPath: 'icons/svgs/docker.svg',
    ogpPath: 'icons/ogps/docker.png',
  },
  {
    id: 8,
    value: '.NET',
    iconPath: 'icons/svgs/dotnetcore.svg',
    ogpPath: 'icons/ogps/dotnetcore.png',
  },
  {
    id: 9,
    value: 'Express',
    iconPath: 'icons/svgs/express.svg',
    ogpPath: 'icons/ogps/express.png',
  },
  {
    id: 10,
    value: 'Flutter',
    iconPath: 'icons/svgs/flutter.svg',
    ogpPath: 'icons/ogps/flutter.png',
  },
  {
    id: 11,
    value: 'Gatsby',
    iconPath: 'icons/svgs/gatsby.svg',
    ogpPath: 'icons/ogps/gatsby.png',
  },
  {
    id: 12,
    value: 'Golang',
    iconPath: 'icons/svgs/go.svg',
    ogpPath: 'icons/ogps/go.png',
  },
  {
    id: 13,
    value: 'GraphQL',
    iconPath: 'icons/svgs/graphql.svg',
    ogpPath: 'icons/ogps/graphql.png',
  },
  {
    id: 14,
    value: 'HTML5',
    iconPath: 'icons/svgs/html5.svg',
    ogpPath: 'icons/ogps/html5.png',
  },
  {
    id: 15,
    value: 'Ionic',
    iconPath: 'icons/svgs/ionic.svg',
    ogpPath: 'icons/ogps/ionic.png',
  },
  {
    id: 16,
    value: 'Java',
    iconPath: 'icons/svgs/java.svg',
    ogpPath: 'icons/ogps/java.png',
  },
  {
    id: 17,
    value: 'JavaScript',
    iconPath: 'icons/svgs/javascript.svg',
    ogpPath: 'icons/ogps/javascript.png',
  },
  {
    id: 18,
    value: 'jQuery',
    iconPath: 'icons/svgs/jquery.svg',
    ogpPath: 'icons/ogps/jquery.png',
  },
  {
    id: 19,
    value: 'Kotlin',
    iconPath: 'icons/svgs/kotlin.svg',
    ogpPath: 'icons/ogps/kotlin.png',
  },
  {
    id: 20,
    value: 'Kubernetes',
    iconPath: 'icons/svgs/kubernetes.svg',
    ogpPath: 'icons/ogps/kubernetes.png',
  },
  {
    id: 21,
    value: 'Laravel',
    iconPath: 'icons/svgs/laravel.svg',
    ogpPath: 'icons/ogps/laravel.png',
  },
  {
    id: 22,
    value: 'Linux',
    iconPath: 'icons/svgs/linux.svg',
    ogpPath: 'icons/ogps/linux.png',
  },
  {
    id: 23,
    value: 'MaterialUi',
    iconPath: 'icons/svgs/materialui.svg',
    ogpPath: 'icons/ogps/materialui.png',
  },
  {
    id: 24,
    value: 'MySQL',
    iconPath: 'icons/svgs/mysql.svg',
    ogpPath: 'icons/ogps/mysql.png',
  },
  {
    id: 25,
    value: 'Next.js',
    iconPath: 'icons/svgs/nextjs.svg',
    ogpPath: 'icons/ogps/nextjs.png',
  },
  {
    id: 26,
    value: 'Node.js',
    iconPath: 'icons/svgs/nodejs.svg',
    ogpPath: 'icons/ogps/nodejs.png',
  },
  {
    id: 27,
    value: 'Nuxt.js',
    iconPath: 'icons/svgs/nuxt.svg',
    ogpPath: 'icons/ogps/nuxt.png',
  },
  {
    id: 28,
    value: 'PHP',
    iconPath: 'icons/svgs/php.svg',
    ogpPath: 'icons/ogps/php.png',
  },
  {
    id: 29,
    value: 'Python',
    iconPath: 'icons/svgs/python.svg',
    ogpPath: 'icons/ogps/python.png',
  },
  {
    id: 30,
    value: 'R',
    iconPath: 'icons/svgs/r.svg',
    ogpPath: 'icons/ogps/r.png',
  },
  {
    id: 31,
    value: 'Rails',
    iconPath: 'icons/svgs/rails.svg',
    ogpPath: 'icons/ogps/rails.png',
  },
  {
    id: 32,
    value: 'React.js',
    iconPath: 'icons/svgs/react.svg',
    ogpPath: 'icons/ogps/react.png',
  },
  {
    id: 33,
    value: 'Ruby',
    iconPath: 'icons/svgs/ruby.svg',
    ogpPath: 'icons/ogps/ruby.png',
  },
  {
    id: 34,
    value: 'Rust',
    iconPath: 'icons/svgs/rust.svg',
    ogpPath: 'icons/ogps/rust.png',
  },
  {
    id: 35,
    value: 'Spring',
    iconPath: 'icons/svgs/spring.svg',
    ogpPath: 'icons/ogps/spring.png',
  },
  {
    id: 36,
    value: 'Swift',
    iconPath: 'icons/svgs/swift.svg',
    ogpPath: 'icons/ogps/swift.png',
  },
  {
    id: 37,
    value: 'Symfony',
    iconPath: 'icons/svgs/symfony.svg',
    ogpPath: 'icons/ogps/symfony.png',
  },
  {
    id: 38,
    value: 'Tomcat',
    iconPath: 'icons/svgs/tomcat.svg',
    ogpPath: 'icons/ogps/tomcat.png',
  },
  {
    id: 39,
    value: 'TypeScript',
    iconPath: 'icons/svgs/typescript.svg',
    ogpPath: 'icons/ogps/typescript.png',
  },
  {
    id: 40,
    value: 'Vue.js',
    iconPath: 'icons/svgs/vuejs.svg',
    ogpPath: 'icons/ogps/vuejs.png',
  },
  {
    id: 41,
    value: 'Webpack',
    iconPath: 'icons/svgs/webpack.svg',
    ogpPath: 'icons/ogps/webpack.png',
  },
  {
    id: 42,
    value: 'Other',
    iconPath: 'icons/svgs/other.svg',
    ogpPath: 'icons/ogps/other.png',
  },
];
